### ISSUE TITLE
Could we get a new release with 0.2.4?

### ISSUE THREAD

**Issue by ghost-pep** [JeffHoogland/Exterminator#5]
I like using this to monitor my Arch system and I decided to maintain the PKGBUILD (I am learning about CS and thought it would be good experience to maintain a package) and it would be best to update the version through a release of 0.2.4. Thanks!

**Comment by JeffHoogland** [comment]
Done. Good suggestion: https://github.com/JeffHoogland/Exterminator/releases/tag/0.2.4
